source 'https://github.com/Cocoapods/Specs.git'
platform :ios, '8.0'

xcodeproj 'iOSRepairApp'

#pod 'ADALiOS', '~> 1.0.0'   # 1.0.0 < ver < 1.1.0
#pod 'Office365/Outlook', '~>0.5.0'
#pod 'Office365/Outlook', '=0.5.4'
#pod 'Office365/Outlook', '=0.8.3'

#first email from josh on 4-25-2015
#pod 'Office365/Outlook', '=0.9.0'
#pod 'ADALiOS', '=1.2.2'

#second email from josh on 4-25-2015
pod 'ADALiOS', '=1.2.2'
pod 'Office365/Outlook', '=0.9.0'
pod 'Office365/Graph', '=0.9.0'
