#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinRepairApp.Resource", IsApplication=true)]

namespace XamarinRepairApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int black = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int blue = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int blue2 = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int gray = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int gray2 = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int gray3 = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int leftBg = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int titleColor = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int tr = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int valueColor = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int white = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int at = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_corner = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int camera = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int close = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int date = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int default_logo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int done_button_corner = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int house = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_repair = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int logo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int logo_incidents = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int person = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int property_logo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int tab = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070011
			public const int detail_back = 2131165201;
			
			// aapt resource value: 0x7f070025
			public const int detail_camera = 2131165221;
			
			// aapt resource value: 0x7f070029
			public const int detail_commentDone = 2131165225;
			
			// aapt resource value: 0x7f070019
			public const int detail_finalizeBtn = 2131165209;
			
			// aapt resource value: 0x7f070020
			public const int detail_incidentDispatcherComments = 2131165216;
			
			// aapt resource value: 0x7f070023
			public const int detail_incidentInspectionComments = 2131165219;
			
			// aapt resource value: 0x7f070027
			public const int detail_incidentRepairComments = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int detail_incidentRepairCommentsEdit = 2131165224;
			
			// aapt resource value: 0x7f070018
			public const int detail_inspectionDate = 2131165208;
			
			// aapt resource value: 0x7f070017
			public const int detail_inspectionEmail = 2131165207;
			
			// aapt resource value: 0x7f070022
			public const int detail_inspectionImages = 2131165218;
			
			// aapt resource value: 0x7f070016
			public const int detail_inspectionName = 2131165206;
			
			// aapt resource value: 0x7f07002c
			public const int detail_largeClose = 2131165228;
			
			// aapt resource value: 0x7f07002b
			public const int detail_largeImage = 2131165227;
			
			// aapt resource value: 0x7f07002a
			public const int detail_largeLayout = 2131165226;
			
			// aapt resource value: 0x7f070015
			public const int detail_propertyAddress = 2131165205;
			
			// aapt resource value: 0x7f070012
			public const int detail_propertyName = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int detail_propertyOwner = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int detail_propertyPhoto = 2131165204;
			
			// aapt resource value: 0x7f070026
			public const int detail_repairImages = 2131165222;
			
			// aapt resource value: 0x7f07001a
			public const int detail_roomTitle = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int detail_roomType = 2131165211;
			
			// aapt resource value: 0x7f07001f
			public const int detail_tab1 = 2131165215;
			
			// aapt resource value: 0x7f070021
			public const int detail_tab2 = 2131165217;
			
			// aapt resource value: 0x7f070024
			public const int detail_tab3 = 2131165220;
			
			// aapt resource value: 0x7f07001c
			public const int detail_tabBtn1 = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int detail_tabBtn2 = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int detail_tabBtn3 = 2131165214;
			
			// aapt resource value: 0x7f070007
			public const int incident_contactOffice = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int incident_contactOwner = 2131165190;
			
			// aapt resource value: 0x7f07000c
			public const int incident_item1 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int incident_item2 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int incident_item3 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int incident_item4 = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int incident_item5 = 2131165200;
			
			// aapt resource value: 0x7f07000b
			public const int incident_item_img = 2131165195;
			
			// aapt resource value: 0x7f070001
			public const int incident_left = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int incident_list = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int incident_middle = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int incident_propertyAddress = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int incident_propertyLogo = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int incident_propertyName = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int incident_propertyOwner = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int incident_right = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int nav_topbg = 2131165184;
			
			// aapt resource value: 0x7f07002f
			public const int signIn_btn = 2131165231;
			
			// aapt resource value: 0x7f07002e
			public const int sign_title = 2131165230;
			
			// aapt resource value: 0x7f07002d
			public const int signin_topbg = 2131165229;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Incident = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Incident_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int IncidentDetail = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int SignIn = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int add_repair_comments = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int app_loading = 2131034114;
			
			// aapt resource value: 0x7f050011
			public const int detail_btnDoneText = 2131034129;
			
			// aapt resource value: 0x7f05000b
			public const int detail_inspection = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int dispatcher = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int finalize_btntext = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int incident_office = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int incident_owner = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int incident_propertytitle = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int incident_title = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public const int inspection = 2131034126;
			
			// aapt resource value: 0x7f050003
			public const int logo_desc = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int signin_btntxt = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int signin_title = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int title_activity_incident = 2131034122;
			
			// aapt resource value: 0x7f050010
			public const int title_activity_incident_detail = 2131034128;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int NoTitle = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
