#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinRepairApp.Resource", IsApplication=true)]

namespace XamarinRepairApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070003
			public const int black = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int blue = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int blue2 = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int gray = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int gray2 = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int gray3 = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int leftBg = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int titleColor = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int tr = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int valueColor = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int white = 2131165186;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_vertical_margin = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int at = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_corner = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int camera = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int close = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int date = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int default_logo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int done_button_corner = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int house = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_repair = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int logo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int logo_incidents = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int person = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int property_logo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int tab = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090031
			public const int action_settings = 2131296305;
			
			// aapt resource value: 0x7f090012
			public const int detail_back = 2131296274;
			
			// aapt resource value: 0x7f090026
			public const int detail_camera = 2131296294;
			
			// aapt resource value: 0x7f09002a
			public const int detail_commentDone = 2131296298;
			
			// aapt resource value: 0x7f09001a
			public const int detail_finalizeBtn = 2131296282;
			
			// aapt resource value: 0x7f090021
			public const int detail_incidentDispatcherComments = 2131296289;
			
			// aapt resource value: 0x7f090024
			public const int detail_incidentInspectionComments = 2131296292;
			
			// aapt resource value: 0x7f090028
			public const int detail_incidentRepairComments = 2131296296;
			
			// aapt resource value: 0x7f090029
			public const int detail_incidentRepairCommentsEdit = 2131296297;
			
			// aapt resource value: 0x7f090019
			public const int detail_inspectionDate = 2131296281;
			
			// aapt resource value: 0x7f090018
			public const int detail_inspectionEmail = 2131296280;
			
			// aapt resource value: 0x7f090023
			public const int detail_inspectionImages = 2131296291;
			
			// aapt resource value: 0x7f090017
			public const int detail_inspectionName = 2131296279;
			
			// aapt resource value: 0x7f09002d
			public const int detail_largeClose = 2131296301;
			
			// aapt resource value: 0x7f09002c
			public const int detail_largeImage = 2131296300;
			
			// aapt resource value: 0x7f09002b
			public const int detail_largeLayout = 2131296299;
			
			// aapt resource value: 0x7f090016
			public const int detail_propertyAddress = 2131296278;
			
			// aapt resource value: 0x7f090013
			public const int detail_propertyName = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int detail_propertyOwner = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int detail_propertyPhoto = 2131296277;
			
			// aapt resource value: 0x7f090027
			public const int detail_repairImages = 2131296295;
			
			// aapt resource value: 0x7f09001b
			public const int detail_roomTitle = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int detail_roomType = 2131296284;
			
			// aapt resource value: 0x7f090020
			public const int detail_tab1 = 2131296288;
			
			// aapt resource value: 0x7f090022
			public const int detail_tab2 = 2131296290;
			
			// aapt resource value: 0x7f090025
			public const int detail_tab3 = 2131296293;
			
			// aapt resource value: 0x7f09001d
			public const int detail_tabBtn1 = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int detail_tabBtn2 = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int detail_tabBtn3 = 2131296287;
			
			// aapt resource value: 0x7f090008
			public const int incident_contactOffice = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int incident_contactOwner = 2131296263;
			
			// aapt resource value: 0x7f09000d
			public const int incident_item1 = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int incident_item2 = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int incident_item3 = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int incident_item4 = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int incident_item5 = 2131296273;
			
			// aapt resource value: 0x7f09000c
			public const int incident_item_img = 2131296268;
			
			// aapt resource value: 0x7f090002
			public const int incident_left = 2131296258;
			
			// aapt resource value: 0x7f09000b
			public const int incident_list = 2131296267;
			
			// aapt resource value: 0x7f090009
			public const int incident_middle = 2131296265;
			
			// aapt resource value: 0x7f090006
			public const int incident_propertyAddress = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int incident_propertyLogo = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int incident_propertyName = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int incident_propertyOwner = 2131296260;
			
			// aapt resource value: 0x7f09000a
			public const int incident_right = 2131296266;
			
			// aapt resource value: 0x7f090001
			public const int nav_topbg = 2131296257;
			
			// aapt resource value: 0x7f090030
			public const int signIn_btn = 2131296304;
			
			// aapt resource value: 0x7f09002f
			public const int sign_title = 2131296303;
			
			// aapt resource value: 0x7f09002e
			public const int signin_topbg = 2131296302;
			
			// aapt resource value: 0x7f090000
			public const int webView1 = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_authentication = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Incident = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Incident_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int IncidentDetail = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int authentication = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int login = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int token = 2131230722;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050007
			public const int ApplicationName = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int SignIn = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int action_settings = 2131034112;
			
			// aapt resource value: 0x7f050014
			public const int add_repair_comments = 2131034132;
			
			// aapt resource value: 0x7f050001
			public const int app_loading = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int broker_authentication_request_is_invalid = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int broker_processing = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int default_not_supported_msg = 2131034114;
			
			// aapt resource value: 0x7f050016
			public const int detail_btnDoneText = 2131034134;
			
			// aapt resource value: 0x7f050010
			public const int detail_inspection = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int dispatcher = 2131034130;
			
			// aapt resource value: 0x7f050003
			public const int error_token_type_not_supported = 2131034115;
			
			// aapt resource value: 0x7f050011
			public const int finalize_btntext = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int incident_office = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int incident_owner = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int incident_propertytitle = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int incident_title = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int inspection = 2131034131;
			
			// aapt resource value: 0x7f050008
			public const int logo_desc = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int signin_btntxt = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int signin_title = 2131034121;
			
			// aapt resource value: 0x7f05000f
			public const int title_activity_incident = 2131034127;
			
			// aapt resource value: 0x7f050015
			public const int title_activity_incident_detail = 2131034133;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int NoTitle = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
